### ISSUE TITLE
Phim is incompatible with PHP 5.5

### ISSUE THREAD

**Issue by forsureitsme** [Talesoft/phim#1]
As described [in composer.json, you specify it works on php >= 5.5.0](https://github.com/Talesoft/phim/blob/master/composer.json#L22).
However, [variadic functions were introduced in PHP 5.6](http://php.net/manual/en/functions.arguments.php#functions.variable-arg-list), making it outright incompatible with PHP < 5.6 when it tries to run the [Color.php:1397](https://github.com/Talesoft/phim/blob/master/src/Phim/Color.php#L1397).

I made it work here for now by using the following WRONG, EVIL CODE in Color.php:1397 

```
return eval('return new '.$className.'('.implode($args).')');
```

So, yeah, you got two choices:
- Update your composer.json to not support php 5.5
- Fix that line(because eval is bad) and get some love from all of us php 5.5 users

**Comment by forsureitsme** [comment]
Fixed in [pull request #2](https://github.com/Talesoft/phim/pull/2).

**Comment by TorbenKoehn** [comment]
Do you need PHP 5.5?

If not, I'd rather make it 5.6+ in the composer.json haha

I actually prefer a variadic over reflection in this case.

See PHP 5.5 official support [ran out already](http://php.net/supported-versions.php) :)

**Comment by forsureitsme** [comment]
It's not just for me, as according to w3techs.com, [around 80% of PHP 5 users/services use PHP 5, and from those 80%, 75% uses PHP < 5.6](https://w3techs.com/technologies/details/pl-php/5/all).

I can't say how many of those actually use Phim. But man, that's 1 line to support a good amount of devs, and it's already "done". Phim is the only library I found who allows me to transform colors through HSL modifiers properly. (Yeah syhol/mrcolor, you suck)

**Comment by TorbenKoehn** [comment]
Well then, there you go :)

Thank you for your contribution!
