### ISSUE TITLE
Deprecation: Phim does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0

### ISSUE THREAD

**Issue by chamby** [Talesoft/phim#13]
> Deprecation Notice: Class Phim\Exception\Runtime\NonExistentFunctionNameException located in ./vendor/talesoft/phim/src/Phim/Exception/Color/NonExistentFunctionNameException.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0.

The namespace and file path do not match:

`Phim\Exception\Runtime\NonExistentFunctionNameException`
vs
`Phim/Exception/Color/NonExistentFunctionNameException.php`

**Comment by TorbenKoehn** [comment]
Thanks for noticing. I'll fix it as soon as I get to it :)

**Comment by chamby** [comment]
@TorbenKoehn I wanted to bump this as Composer v2 is imminent.

**Comment by TorbenKoehn** [comment]
@chamby Fixed this in 1.0.6, can you test?

**Comment by chamby** [comment]
The warning went away for Composer 1.x and the file was not skipped for Composer 2.x.

I was able to make use of the Exception using the `Phim\Exception\Color\NonExistentFunctionNameException` namespace.
