### ISSUE TITLE
parseHexString outputs wrong RgbColor

### ISSUE THREAD

**Issue by barryvanveen** [Talesoft/phim#5]
Hi!

First of all, thank you for this package, it looks great! And up till now I thought it was working fine as well, but I think I found a problem with parsing hexadecimal strings :)

When I convert `#6BBAA7` to RGB with a random online tool the output is always RGB(107, 186, 167). 
The output of `\Phim\Color::get("#6BBAA7")->toRgb()` is `RBG(0, 107, 186)`. As you can see the values seem to be offset, this corresponds to `#006BBA` and is not correct. 

It looks to me like `Phim/Color::parseInt` outputs the incorrect result but why this is the case... The results can easily be fixed by adding the following case to `Phim/Color::parseHexString`:

```php
case 6:
    return new RgbColor(
        hexdec($string[0].$string[1]),
        hexdec($string[2].$string[3]),
        hexdec($string[4].$string[5])
    );
```

What do you think think is the correct fix and would you be interested in me making a pull request?

Cheers,

Barry

**Comment by TorbenKoehn** [comment]
Hello,

seems using hexdec on the whole string doesn't give the correct result at all then. The fix looks okay, it's how it used to work until I patched that bug in

Feel free to create a PR and I'll patch it in!

**Comment by barryvanveen** [comment]
@TorbenKoehn, could you have a look the PR I've opened up?

Thanks,

Barry

**Comment by TorbenKoehn** [comment]
The PR is merged in. Is this issue solved for you?

When you tested it, too, and it works, I'll add a new release :)

**Comment by barryvanveen** [comment]
Thank you very much Torben, this fixes the issue in my project! Looking forward to the new release :)

**Comment by TorbenKoehn** [comment]
Check out Release 1.0.3!

Thanks for your contribution :)
