### ISSUE TITLE
Documentation: incorrect method for toHexString()

### ISSUE THREAD

**Issue by justincone** [Talesoft/phim#7]
Under the [Color information section of the documentation](https://github.com/Talesoft/phim#color-information), it says to use getHexString() for fetching the hex value of a color, but I believe the correct method is toHexString().

Apologies if I'm mistaken! Thanks for the fantastic work. 😸

**Comment by TorbenKoehn** [comment]
Thank you for reporting this, it is fixed. You were not mistaken :)
