### ISSUE TITLE
Color difference with black or white throws division by zero error

### ISSUE THREAD

**Issue by justincone** [Talesoft/phim#8]
# Steps to reproduce

`$baseDifferenceFromBlack = Color::getDifference(Color::get('red'), Color::get('black'));`

or

`$baseDifferenceFromBlack = Color::getDifference(Color::get('red'), Color::get('white'));`

# Expected result
The calculated difference of a given color and either black or white.

# Actual result
Both expressions above throw a division by zero error referencing line 1723 of Color.php:

`return rad2deg(atan($b / $a)) + $bias;`

**Comment by TorbenKoehn** [comment]
Thank you @justincone for reporting this, this is fixed with @kylekatarnls PR in the new release. Thank you @kylekatarnls for fixing it :)
